import React, { useState } from "react";
import { useLocation } from "react-router-dom";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { useToken } from "../../auth/useToken";
import {
  Card,
  CardBody,
  CardHeader,
  Container,
  Button,
  Row,
  Col,
} from "reactstrap";

const Qr = () => {
  const location = useLocation();
  const secretImageUri = location.state.secretImageUri;
  const [otpCode, setOtpCode] = useState("");
  const [message, setMessage] = useState("");

  const recievedData = location.state;
  const [token, setToken] = useToken();
  const navigate = useNavigate();
  console.log(recievedData.email);
  const verifyMFACode = async (event) => {
    event.preventDefault();
    const response = await axios.post(
      "http://localhost:8080/api/v1/auth/verify",
      {
        email: recievedData.email,
        code: otpCode,
      }
    );
    if (response.status === 200) {
      const jwt_token = response.data["accessToken"];
      setToken(jwt_token);
      navigate("/");
    }
  };

  return (
    <Container>
      <Row className="mt-4">
        <Col sm={{ size: 5, offset: 3 }}>
          <Card color="dark" inverse>
            <CardHeader>
              <h5>Scan the QR Code:</h5>
            </CardHeader>
            <CardBody>
              <img src={secretImageUri} alt="QR Code" />
            </CardBody>
          </Card>
          <Card color="dark" inverse>
            <CardHeader>
              <h5>Enter 6 digits Validation Code Generated by the app:</h5>
            </CardHeader>
            <CardBody>
              <input
                type="text"
                id="validationCode"
                name="validationCode"
                required
                value={otpCode}
                onChange={(e) => setOtpCode(e.target.value)}
              />
            </CardBody>
            <Container className="text-center">
                    <Button outline color="light" onClick={verifyMFACode} className={otpCode.length < 6 ? "button-disabled" : ""}>
                    Verify code
                    </Button>
                  </Container>
          </Card>
        </Col>
      </Row>
    </Container>

/* <>
<div>Scan the QR Code:</div>
    <div>
      <img src={secretImageUri} alt="QR Code" />
    </div>
    <div className="form-group">
      <label htmlFor="validationCode">
        Enter 6 digits Validation Code Generated by the app
      </label>
      <input
        type="text"
        id="validationCode"
        name="validationCode"
        required
        value={otpCode}
        onChange={(e) => setOtpCode(e.target.value)}
      />
    </div>
    <button
      type="button"
      onClick={verifyMFACode}
      className={otpCode.length < 6 ? "button-disabled" : ""}
    >
      Verify code
    </button>
    <div>{message}</div>

</>
     */
  );
};
export default Qr;
